name: build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-

      - run: yarn install --frozen-lockfile

      - run: yarn build
        env:
          DROPBOX_API_KEY: ${{ secrets.DROPBOX_API_KEY }}
          DROPBOX_API_SECRET: ${{ secrets.DROPBOX_API_SECRET }}
          GOOGLE_DRIVE_API_KEY: ${{ secrets.GOOGLE_DRIVE_API_KEY }}
          GOOGLE_DRIVE_API_SECRET: ${{ secrets.GOOGLE_DRIVE_API_SECRET }}

      - run: yarn lint

      - run: yarn test

      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
